version: '{build}'
clone_depth: 1
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TARGET: x86_64-pc-windows-msvc
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
for:
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    install:
      - cmd: >-
          curl -sSf -o rust-install.exe https://static.rust-lang.org/dist/rust-nightly-%TARGET%.exe

          rust-install.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"

          set PATH=%PATH%;C:\Program Files (x86)\Rust\bin

          rustc -V

          cargo -V

    build_script:
      - cmd: >-

          echo "Hello, Windows!"

  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    install:
      - sh: >-
          curl -sSf -o rustup.sh https://sh.rustup.rs | sh -s -- --quiet --default-host x86_64-unknown-linux-gnu --default-toolchain stable --profile default -y

          rustc -V

          cargo -V

    build_script:
      - sh: >-
          echo "Hello, Ubuntu!"

  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: macOS
    install:
      - sh: >-
          curl -sSf -o rustup.sh https://sh.rustup.rs

          bash rustup.sh --quiet

          rustup default stable

          rustc -V

          cargo -V

    build_script:
      - sh: >-
          echo "Hello, macOS!"

