version: '{build}'
clone_depth: 1
image:
  - Visual Studio 2019
  - Ubuntu
  - macOS
for:
  -
    matrix:
      only:
        - image: Visual Studio 2019
    build_script:
      - cmd: >-
        Write-Host "Hello, Windows!"
        Write-Host "Hello, Windows!"
  -
    matrix:
      only:
        - image: Ubuntu
    build_script:
      - sh: >-
        echo "Hello, Ubuntu!"
        echo "Hello, Ubuntu!"
  -
    matrix:
      only:
        - image: macOS
    build_script:
      - sh: >-
        echo "Hello, macOS!"
        echo "Hello, macOS!"
