version: '{build}'
clone_depth: 1
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TARGET: x86_64-pc-windows-msvc
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      TARGET: foo
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
      TARGET: bar
for:
  -
    matrix:
      only:
        - image: Visual Studio 2019
    install:
      - cmd: >-
          curl -sSf -o rust-install.exe   https://static.rust-lang.org/dist/rust-nightly-%TARGET%.exe

          rust-install.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"

          set PATH=%PATH%;C:\Program Files (x86)\Rust\bin

          rustc -V

          cargo -V


    build_script:
      - cmd: >-
          echo "Hello, Windows!"

          echo "Hello, Windows!"
  -
    matrix:
      only:
        - image: Ubuntu
    install:
      - sh: >-
          echo "$TARGET"
    build_script:
      - sh: >-
          echo "Hello, Ubuntu!"

          echo "Hello, Ubuntu!"
  -
    matrix:
      only:
        - image: macOS
    install:
      - sh: >-
          echo "$TARGET"
    build_script:
      - sh: >-
          echo "Hello, macOS!"

          echo "Hello, macOS!"
