version: '{build}'
clone_depth: 1
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      HOST: x86_64-unknown-linux-gnu
      TARGET: x86_64-unknown-linux-gnu
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      HOST: x86_64-unknown-linux-gnu
      TARGET: wasm32-unknown-unknown
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
      HOST: x86_64-apple-darwin
      TARGET: x86_64-apple-darwin
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      HOST: x86_64-pc-windows-msvc
      TARGET: x86_64-pc-windows-msvc
for:
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          TARGET: x86_64-unknown-linux-gnu
    install:
      - sh: >-
          curl -sSf https://sh.rustup.rs | sh -s -- --quiet --default-host $HOST --default-toolchain stable --profile minimal -y

          export PATH="$HOME/.cargo/bin:$PATH"

          rustc -V

          cargo -V

    build_script:
      - sh: >-
          cargo build --manifest-path=graphical/Cargo.toml

          cargo build --manifest-path=ansi-terminal/Cargo.toml

  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          TARGET: wasm32-unknown-unknown
    install:
      - sh: >-
          curl -sSf https://sh.rustup.rs | sh -s -- --quiet --default-host $HOST --default-toolchain stable --profile minimal -y

          export PATH="$HOME/.cargo/bin:$PATH"

          rustup target add $TARGET

          cargo install wasm-bindgen-cli --force --version 0.2.55 # this has to match the version in Cargo.lock

          rustc -V

          cargo -V

    build_script:
      - sh: >-
          pushd web

          npm install

          npm run build -- --mode development

  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: macOS
          TARGET: x86_64-apple-darwin
    install:
      - sh: >-
          curl -sSf https://sh.rustup.rs | sh -s -- --quiet --default-host $HOST --default-toolchain stable --profile minimal -y

          export PATH="$HOME/.cargo/bin:$PATH"

          rustc -V

          cargo -V

    build_script:
      - sh: >-
          cargo build --manifest-path=graphical/Cargo.toml

          cargo build --manifest-path=ansi-terminal/Cargo.toml
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          TARGET: x86_64-pc-windows-msvc
    install:
      - cmd: >-
          appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe

          rustup-init -yv --default-toolchain stable --default-host %HOST%

          set PATH=%PATH%;%USERPROFILE%\.cargo\bin

          rustc -V

          cargo -V

    build_script:
      - cmd: >-
          cargo build --manifest-path=graphical/Cargo.toml

