version: '{build}'
clone_depth: 1
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      TARGET: x86_64-unknown-linux-gnu
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      TARGET: wasm32-unknown-unknown
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
      TARGET: x86_64-apple-darwin
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TARGET: x86_64-pc-windows-msvc
for:
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    install:
      - sh: >-
          curl -sSf https://sh.rustup.rs | sh -s -- --quiet --default-host $TARGET --default-toolchain stable --profile minimal -y

          export PATH="$HOME/.cargo/bin:$PATH"

          rustc -V

          cargo -V

    build_script:
      - sh: >-
          echo "Hello, Ubuntu!"

  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: macOS
    install:
      - sh: >-
          curl -sSf https://sh.rustup.rs | sh -s -- --quiet --default-host $TARGET --default-toolchain stable --profile minimal -y

          export PATH="$HOME/.cargo/bin:$PATH"

          rustc -V

          cargo -V

    build_script:
      - sh: >-
          echo "Hello, macOS!"
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    install:
      - cmd: >-
          curl -sSf -o rust-install.exe https://static.rust-lang.org/dist/rust-stable-%TARGET%.exe

          rust-install.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"

          set PATH=%PATH%;C:\Program Files (x86)\Rust\bin

          rustc -V

          cargo -V

    build_script:
      - cmd: >-

          echo "Hello, Windows!"


